### ISSUE TITLE
Replace all instances of "IIC" and "Institutional Innovation Council" with "IT Club, Department of Computer Applications" in Footer.js

### ISSUE THREAD

**Issue by kshavp** [iicsrm/web#11]
Steps to reproduce:

• open **Footer.js**
• search for all keywords with "IIC" or "Institutional Innovation Council"
• replace the fields with "IT Club, Department of Computer Applications"
• Commit, push and create pull request to be reviewed.

- [ ] IT Club, Department of Computer Applications appearing on the website footer after the changes.

**Comment by SartHak-0-Sach** [comment]
I am sorry if I am unable to understand what you mean but in footer.js there is only one IIC written that according to you is the issue and needs to be replaced to IT Club, Department of Computer Applications. Is that it?
